// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wpf_mvvm_test.DB;

namespace wpf_mvvm_test.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("wpf_mvvm_test.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("TokenValue")
                        .HasColumnType("varchar(36) CHARACTER SET utf8mb4")
                        .HasMaxLength(36);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "testemail@gmail.com",
                            Name = "test",
                            Password = "12345",
                            TokenValue = "d6ce67f2-0915-4298-bce8-aa00d8472a59"
                        },
                        new
                        {
                            Id = 2,
                            Email = "test2email@gmail.com",
                            Name = "test2",
                            Password = "12345",
                            TokenValue = "12152273-dc8e-4cb2-a2d1-6599b91b976f"
                        },
                        new
                        {
                            Id = 3,
                            Email = "test3email@gmail.com",
                            Name = "test3",
                            Password = "12345",
                            TokenValue = "cfdb36d4-de14-42c9-8ca1-1f3f2ef78845"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
